In [1]:
# Ufunct in numpy
import numpy as np

def myadd(x, y):
    return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([ 4, 3, 2], [ 6, 7, 8]))

[10 10 10]


In [2]:
# type Ufunc
import numpy as np
print(type(np.add))
print(type(np.concatenate))

<class 'numpy.ufunc'>
<class 'builtin_function_or_method'>


In [3]:
# Simple Arithmetic Functions
import numpy as np
arr1 = np.array([10, 11, 12, 13, -14, -15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))
print(np.power(arr1,arr2))
print(np.mod(arr1,arr2))
print(np.remainder(arr1,arr2))
print(np.divmod(arr1,arr2))
print(np.abs(arr1))

[30 32 34 36 10 10]
[-10 -10 -10 -10 -38 -40]
[ 200  231  264  299 -336 -375]
[ 0.5         0.52380952  0.54545455  0.56521739 -0.58333333 -0.6       ]
[1661992960  602408795          0 1487897765 1090519040 1144744561]
[10 11 12 13 10 10]
[10 11 12 13 10 10]
(array([ 0,  0,  0,  0, -1, -1], dtype=int32), array([10, 11, 12, 13, 10, 10], dtype=int32))
[10 11 12 13 14 15]


In [4]:
# Rounding Decimals
import numpy as np
print(np.trunc([30.1624,0.23145]))
print(np.fix([30.1624,0.23145]))
print(np.around(30.2146534,2))
print(np.floor([30.2146534,2]))
print(np.ceil([30.1624,0.23145]))

[30.  0.]
[30.  0.]
30.21
[30.  2.]
[31.  1.]


In [5]:
# Logs
import numpy as np
import math
print(np.log(np.arange(1,10))) #log e
print(np.log2(np.arange(1,10))) #log 2
print(np.log10(np.arange(1,10))) #log 10
print(np.frompyfunc(math.log, 2, 1)(10,15))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
0.8502741537276026


In [6]:
# Summations
import numpy as np
arr1 = np.array([10, 11, 12, 13, -14, -15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.sum([arr1, arr2],axis=0)
print(newarr)
newarr = np.cumsum(arr2)
print(newarr)

[30 32 34 36 10 10]
[ 20  41  63  86 110 135]
