In [1]:
import numpy as np
a = np.array([[1,2,3,4,5,8],[1,5,2,3,4,10]])
b = np.array([[1,2,3,4,5,8],[1,5,2,3,4,10]])
print(a,a.ndim,a.dtype,a.itemsize,a.size,
      a.shape,np.linspace(5,9,5),a.reshape(6,2)
      ,a.max(),a.min(),a.sum(),a.max(axis=0),
      a.sum(axis=0),a.max(axis=1),
      a.sum(axis=1),np.std(a),
      np.vstack((a,b)),np.hstack((a,b)),sep="\n")

[[ 1  2  3  4  5  8]
 [ 1  5  2  3  4 10]]
2
int32
4
12
(2, 6)
[5. 6. 7. 8. 9.]
[[ 1  2]
 [ 3  4]
 [ 5  8]
 [ 1  5]
 [ 2  3]
 [ 4 10]]
10
1
48
[ 1  5  3  4  5 10]
[ 2  7  5  7  9 18]
[ 8 10]
[23 25]
2.614064523559687
[[ 1  2  3  4  5  8]
 [ 1  5  2  3  4 10]
 [ 1  2  3  4  5  8]
 [ 1  5  2  3  4 10]]
[[ 1  2  3  4  5  8  1  2  3  4  5  8]
 [ 1  5  2  3  4 10  1  5  2  3  4 10]]


In [2]:
import numpy as np
d = np.dtype([("Salary",np.float64)])
print(d)
arr = np.array([(10000.12,),(15000.02,)],dtype=d)
print(arr.dtype,arr)

[('Salary', '<f8')]
[('Salary', '<f8')] [(10000.12,) (15000.02,)]


In [3]:
#The empty routine is used to create an uninitialized array of specified shape and data type
import numpy as np
arr1 = np.empty((3,2),dtype=int)
print(arr1)


[[ 1  5]
 [ 3  4]
 [ 5 10]]


In [4]:
# This routine is used to create the numpy array with the specified shape where each numpy array item is initialized to 0
import numpy as np
arr1=np.zeros((3,2),dtype=int)
print(arr1)

[[0 0]
 [0 0]
 [0 0]]


In [5]:
# This routine is used to create the numpy array with the specified shape where each numpy array item is initialized to 1
import numpy as np
arr1=np.ones((3,3),dtype=int)
print(arr1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
# array from list,tuples
import numpy as np
a=(1,2,3,4,5,6)
b=[1,2,3,4,5,6]
aa=np.asarray(a,dtype=int)
bb=np.asarray(b,dtype=int)
print(aa,bb,sep="\n")

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [10]:
# array from buffer
import numpy as np
a= b'iammkkrishna21071998'
print(type(a))
aa=np.frombuffer(a,dtype='S1',count=-1)
print(aa,type(aa))

<class 'bytes'>
[b'i' b'a' b'm' b'm' b'k' b'k' b'r' b'i' b's' b'h' b'n' b'a' b'2' b'1'
 b'0' b'7' b'1' b'9' b'9' b'8'] <class 'numpy.ndarray'>


In [8]:
# array from iterator
import numpy as np
a=[1,2]
print(a,type(a),sep="\n")
aa=np.fromiter(a,dtype=int)
print(aa,type(aa))

[1, 2]
<class 'list'>
[1 2] <class 'numpy.ndarray'>


In [9]:
# Numpy Arrays within the numerical range
import numpy as np
#arange
a=np.arange(6,11,1,float)
print(a)
b=np.linspace(6,10,5)
print(b)
c=np.logspace(6,10,5,endpoint=True)
print(c)

[ 6.  7.  8.  9. 10.]
[ 6.  7.  8.  9. 10.]
[1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]


In [10]:
#iter an array
import numpy as np
a=np.array([[1,2,3,50],[1,3,5,60]],order='F')
print(a)
for i in np.nditer(a):
    print(i,end=" ")
print("\n",a,end='\n')

b=a.T
print('\n')
print(b)
for i in np.nditer(b ,op_flags = ['readwrite']):
    i[...]=i*3
    print(i,sep=" ",end=" ")
print(b)

[[ 1  2  3 50]
 [ 1  3  5 60]]
1 1 2 3 3 5 50 60 
 [[ 1  2  3 50]
 [ 1  3  5 60]]


[[ 1  1]
 [ 2  3]
 [ 3  5]
 [50 60]]
3 3 6 9 9 15 150 180 [[  3   3]
 [  6   9]
 [  9  15]
 [150 180]]


In [11]:
# binary representation

import numpy as np
a=20
b=5
print(np.binary_repr(a),np.binary_repr(np.right_shift(a,3)),np.binary_repr(b),np.binary_repr(np.left_shift(b,3)))
print(np.bitwise_or(a,b),np.bitwise_and(a,b),np.invert(a),np.binary_repr(a,b))

10100 10 101 101000
21 4 -21 10100


In [12]:
#string operations
import numpy as np
s="this is javadi sai krishna"
a=np.char.add(('iam krishna '),('iam so ,called'))
print(a,np.char.multiply('H ',5),sep='\n')
print(np.char.center('nsnsacsajc',15))
print(np.char.capitalize('nsnsacsajc'))
print(np.char.title('nsnsacsajc hx xjAXJH aascnas csca'))
print(np.char.lower('nsnsacsajc hx xjAXJH aascnas csca'))
print(np.char.upper('nsnsacsajc hx xjAXJH aascnas csca'))
print(np.char.split('nsnsacsajc hx xjAXJH aascnas csca'),sep=" ")
print(np.char.splitlines('nsnsacsajc\nhx\nxjAXJH\naascnas csca'))
print(np.char.lstrip('   nsnsacsajc hx xjAXJH aascnas csca   '))
print('   nsnsacsajc hx xjAXJH aascnas csca   ')
print(np.char.join(':..:','nsnsacsajc'))
print(np.char.replace(s,'javadi','javvadi'))
se=np.char.encode(s,'cp500')
print(se)
print(np.char.decode(se,'cp500'))

iam krishna iam so ,called
H H H H H 
   nsnsacsajc  
Nsnsacsajc
Nsnsacsajc Hx Xjaxjh Aascnas Csca
nsnsacsajc hx xjaxjh aascnas csca
NSNSACSAJC HX XJAXJH AASCNAS CSCA
['nsnsacsajc', 'hx', 'xjAXJH', 'aascnas', 'csca']
['nsnsacsajc', 'hx', 'xjAXJH', 'aascnas csca']
nsnsacsajc hx xjAXJH aascnas csca   
   nsnsacsajc hx xjAXJH aascnas csca   
n:..:s:..:n:..:s:..:a:..:c:..:s:..:a:..:j:..:c
this is javvadi sai krishna
b'\xa3\x88\x89\xa2@\x89\xa2@\x91\x81\xa5\x81\x84\x89@\xa2\x81\x89@\x92\x99\x89\xa2\x88\x95\x81'
this is javadi sai krishna


In [13]:
# trignometric functions
import numpy as np
a=np.array([0,30,45,60,90])
sin=np.sin(a*np.pi/180)
cos=np.cos(a*np.pi/180)
tan=np.tan(a*np.pi/180)
cot=np.arctan(tan)
sec=np.arccos(cos)
cosec=np.arcsin(sin)
print(sin,cos,tan,cot,sec,cosec,sep='\n')
print(np.degrees(cot),np.degrees(sec),np.degrees(cosec),sep='\n')

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[ 0. 30. 45. 60. 90.]
[ 0. 30. 45. 60. 90.]
[ 0. 30. 45. 60. 90.]


In [14]:
#around,ceil,floor
import numpy as np
a=[12.014,52.045,85.41,1.24]
print(np.around(a,2),np.ceil(a),np.floor(a))

[12.01 52.04 85.41  1.24] [13. 53. 86.  2.] [12. 52. 85.  1.]


In [15]:
#statistical functions
import numpy as np
a=np.array([[1,5,3],[7,5,6],[4,8,9]])
print(a.max(),np.amax(a),a.min(),np.amin(a))
print(a.max(axis=0),np.amax(a,0),a.min(axis=0),np.amin(a,0))
print(a.max(axis=1),np.amax(a,1),a.min(axis=1),np.amin(a,1))

9 9 1 1
[7 8 9] [7 8 9] [1 5 3] [1 5 3]
[5 7 9] [5 7 9] [1 5 4] [1 5 4]


In [16]:
#peaktopeak
import numpy as np
a=np.array([[1,5,3],[7,5,6],[1,8,9]])
print(np.ptp(a,0),np.ptp(a,1))
print(np.percentile(a,10,0),np.percentile(a,10,1))
print(np.median(a,0),np.mean(a,0),np.average(a,0))
print(np.median(a,1),np.mean(a,1),np.average(a,1))

[6 3 6] [4 2 8]
[1.  5.  3.6] [1.4 5.2 2.4]
[1. 5. 6.] [3. 6. 6.] [3. 6. 6.]
[3. 6. 8.] [3. 6. 6.] [3. 6. 6.]


In [17]:
# sorting
import numpy as np
a=np.array([[1,5,6],[7,5,3],[1,8,9]])
print(np.sort(a),np.sort(a,0),sep="\n")

[[1 5 6]
 [3 5 7]
 [1 8 9]]
[[1 5 3]
 [1 5 6]
 [7 8 9]]


In [18]:
# array sorting by name
import numpy as np
data_type=np.dtype([('Name','S10'),('Marks',int)])
arr=np.array([('Sai',91),('Krishna',84)],dtype=data_type)
print(arr)
print(np.sort(arr,order='Marks'))

[(b'Sai', 91) (b'Krishna', 84)]
[(b'Krishna', 84) (b'Sai', 91)]


In [19]:
import numpy as np  
  
a = np.array([90, 29, 89, 12])  
  
print("Original array:\n",a)  
  
sort_ind = np.argsort(a)  
  
print("Printing indices of sorted data\n",sort_ind)  
  
sort_a = a[sort_ind]  
  
print("printing sorted array")

  
for i in sort_ind:  
    print(a[i],end = " ")  

Original array:
 [90 29 89 12]
Printing indices of sorted data
 [3 1 2 0]
printing sorted array
12 29 89 90 

In [20]:
import numpy as np  
  
a = np.array(['a','b','c','d','e'])  
  
b = np.array([12, 90, 380, 12, 211])  
  
ind = np.lexsort((a,b))  
  
print("printing indices of sorted data")  
  
print(ind)  
  
print("using the indices to sort the array")  
  
for i in ind:  
    print(a[i],b[i])  


printing indices of sorted data
[0 3 1 4 2]
using the indices to sort the array
a 12
d 12
b 90
e 211
c 380


In [21]:
import numpy as np  
  
b = np.array([12, 90, 380, 12, 211])  
  
print(np.where(b>12))  
  
c = np.array([[20, 24],[21, 23]])  
  
print(np.where(c>20)) 

(array([1, 2, 4], dtype=int64),)
(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))


In [22]:
# matlib marix lib
import numpy as np
from numpy import matlib as ms
print(ms.empty((2,3)),sep='\n')
print(ms.zeros((2,3)))
print(ms.ones((2,3)))


[[0.e+000 5.e-324 5.e-324]
 [0.e+000 5.e-324 5.e-324]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
import numpy as np
from numpy import matlib as ms
print(ms.eye(3,3,0,float))
print(ms.identity(4,int))
print(ms.rand(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[0.04397178 0.26575821 0.74812014]
 [0.42773902 0.39097681 0.79828524]
 [0.22995877 0.33825525 0.9963576 ]]


In [24]:
#linear algebra
import numpy as np  
a = np.array([[23,12,10],[7,8,9],[7,8,9]],order='F')  
b = np.array([[10,20,15],[8,9,7],[7,8,9]],order='C')  
dot = np.dot(a,b)  
print(a,b,dot,np.vdot(a,b),np.inner(a,b),np.matmul(a,b),sep='\n') 

[[23 12 10]
 [ 7  8  9]
 [ 7  8  9]]
[[10 20 15]
 [ 8  9  7]
 [ 7  8  9]]
[[396 648 519]
 [197 284 242]
 [197 284 242]]
1005
[[620 362 347]
 [365 191 194]
 [365 191 194]]
[[396 648 519]
 [197 284 242]
 [197 284 242]]


In [25]:
#linear algebra
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print(a,np.linalg.det(a),np.linalg.solve(a,b),np.linalg.inv(a),sep='\n')

[[1 2]
 [3 4]]
-2.0000000000000004
[[1. 0.]
 [0. 1.]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [26]:
# matrix multiplication
import numpy as np
a=np.array([[1,2,3],[6,5,4],[8,5,2]],ndmin=3)
b=np.array([[1,2,3],[6,5,4],[8,5,2]],ndmin=3)
print(np.multiply(a,b),np.matmul(a,b),np.dot(a,b),sep='\n')

[[[ 1  4  9]
  [36 25 16]
  [64 25  4]]]
[[[37 27 17]
  [68 57 46]
  [54 51 48]]]
[[[[37 27 17]]

  [[68 57 46]]

  [[54 51 48]]]]


In [24]:
import numpy as np
s=b'iam krishna'
df=np.frombuffer(s,dtype='S1')
df

array([b'i', b'a', b'm', b' ', b'k', b'r', b'i', b's', b'h', b'n', b'a'],
      dtype='|S1')